### ISSUE TITLE
node: command not found

### ISSUE THREAD

**Issue by whitfin** [obiwankenoobi/TinyScratchpad.js#3]
Looks like this doesn't bundle Node.js and so relies on Node.js to be installed. Whilst this is understandable, it doesn't detect the Node.js I have installed and there's no way to configure the path to the `node` executable.

I think either `node` should be bundled (via something like [this](https://www.npmjs.com/package/node)) , or there should be some configuration options to provide the path to your `node` executable.

My Node.js is installed via `asdf` and exists in my path. There is also a link inside `/usr/local/bin/node`, but that isn't found either.

**Comment by iamwillow** [comment]
I am also experiencing `zsh: command not found: node`. Thanks for bringing this up.

**Comment by obiwankenoobi** [comment]
@whitfin Thanks, will try to think about an idea to solve it

**Comment by obiwankenoobi** [comment]
@iamwillow @whitfin I believe I have found a solution. 

on the first line in the editor specify the path to your node binary like that:

```
/* /usr/local/bin/node */

console.log("should work")
```
**note** The path must be written in the first line.

If you can clone the repo and try to build `master` to test it on your machine to see if it works for you it will be great. Let me know and I will deploy new release if it does.

**Comment by obiwankenoobi** [comment]
I am closing it now, new release has been deployed. Please reopen if you still have issues with that.
